name: Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust Toolchain
        run: |
          rustup default nightly
          rustup component add clippy
      - name: Check clippy
        run: |
          cargo clippy --all-features --all-targets -- -Dwarnings
      - name: Check Docs
        run: |
          cargo doc --workspace --all-features --no-deps
